### ISSUE TITLE
Fix Node.js version

### ISSUE THREAD

**Issue by inductor** [beakman/medusa-stack-dockerized#1]
According to [medusa doc](https://docs.medusajs.com/usage/create-medusa-app#nodejs), Node.js 14 and 16 are supported, but your Dockerfile is 17 based.

**Comment by beakman** [comment]
Thank you very much for you comment @inductor. I'm using the official [medusa-starter](https://github.com/medusajs/medusa-starter-default/blob/master/Dockerfile) as a git submodule, which uses that node version. Maybe the documentation is not updated.
